alert-combiner-py/README.md, alert-combiner-py/package-lock.json, alert-combiner-py/package.json, alert-combiner-py/publish.log, alert-combiner-py/src/constants.py
=> Incorporate-aztec-bot

malicious-smart-contract-ml-v3-py/.gitignore, malicious-smart-contract-ml-v3-py/publish.log, malicious-smart-contract-ml-v3-py/src/agent.py, malicious-smart-contract-ml-v3-py/src/agent_test.py, malicious-smart-contract-ml-v3-py/src/constants.py, malicious-smart-contract-ml-v3-py/src/findings.py, malicious-smart-contract-ml-v3-py/src/utils.py, malicious-smart-contract-ml-v3-py/src/web3_mock.py
- Use creation bytecode instead of runtime for contracts created by EOAs
- Calculate anomaly score for the attack detector
- Remove sighashes from metadata (already included in the logs)
=> Malicious Smart Contract Updates

anomalous-token-transfers-ml-py/.gitignore, anomalous-token-transfers-ml-py/README.md, anomalous-token-transfers-ml-py/package-lock.json, anomalous-token-transfers-ml-py/publish.log, anomalous-token-transfers-ml-py/requirements.txt, anomalous-token-transfers-ml-py/src/agent.py, anomalous-token-transfers-ml-py/src/agent_test.py, anomalous-token-transfers-ml-py/src/utils/constants.py, anomalous-token-transfers-ml-py/src/utils/data_processing.py, anomalous-token-transfers-ml-py/src/utils/findings.py, malicious-smart-contract-ml-py/.gitignore, malicious-smart-contract-ml-py/package-lock.json, malicious-smart-contract-ml-py/package.json, malicious-smart-contract-ml-py/publish.log, malicious-smart-contract-ml-py/requirements.txt, malicious-smart-contract-ml-py/src/agent.py, malicious-smart-contract-ml-py/src/agent_test.py, malicious-smart-contract-ml-py/src/constants.py, malicious-smart-contract-ml-py/src/findings.py, malicious-smart-contract-ml-py/src/utils.py, malicious-smart-contract-ml-py/src/web3_mock.py, malicious-smart-contract-ml-v3-py/src/utils.py, malicious-token-contract-ml-py/.gitignore, malicious-token-contract-ml-py/publish.log, malicious-token-contract-ml-py/requirements.txt, malicious-token-contract-ml-py/src/agent.py, malicious-token-contract-ml-py/src/constants.py, malicious-token-contract-ml-py/src/findings.py, malicious-token-contract-ml-py/src/utils.py, malicious-token-contract-ml-py/src/web3_mock.py
=> Add anomaly scores

anomalous-token-transfers-ml-py/README.md, anomalous-token-transfers-ml-py/publish.log, anomalous-token-transfers-ml-py/requirements.txt, anomalous-token-transfers-ml-py/src/agent.py, anomalous-token-transfers-ml-py/src/agent_test.py, anomalous-token-transfers-ml-py/src/utils/constants.py, anomalous-token-transfers-ml-py/src/utils/data_processing.py, malicious-smart-contract-ml-py/.gitignore, malicious-smart-contract-ml-py/requirements.txt, malicious-smart-contract-ml-py/src/agent.py, malicious-smart-contract-ml-py/src/constants.py, malicious-smart-contract-ml-py/src/utils.py, malicious-smart-contract-ml-v3-py/.gitignore, malicious-smart-contract-ml-v3-py/requirements.txt, malicious-smart-contract-ml-v3-py/src/agent.py, malicious-smart-contract-ml-v3-py/src/constants.py, malicious-smart-contract-ml-v3-py/src/utils.py, malicious-token-contract-ml-py/.gitignore, malicious-token-contract-ml-py/requirements.txt, malicious-token-contract-ml-py/src/agent.py, malicious-token-contract-ml-py/src/constants.py, malicious-token-contract-ml-py/src/utils.py
Update labels + replace luabase
=> Remove luabase and update labels

anomalous-token-transfers-ml-py/.gitignore, anomalous-token-transfers-ml-py/publish.log, anomalous-token-transfers-ml-py/requirements.txt, anomalous-token-transfers-ml-py/src/agent.py, anomalous-token-transfers-ml-py/src/agent_test.py, anomalous-token-transfers-ml-py/src/utils/data_processing.py, anomalous-token-transfers-ml-py/src/utils/findings.py, cex-funding-py/.gitignore, cex-funding-py/publish.log, cex-funding-py/requirements.txt, cex-funding-py/src/agent.py, cex-funding-py/src/agent_test.py, cex-funding-py/src/findings.py
=> Update all python bots to use bot alert rate package

anomalous-token-transfers-ml-py/package-lock.json, anomalous-token-transfers-ml-py/package.json, malicious-account-funding-py/package-lock.json, malicious-account-funding-py/package.json, malicious-account-funding-py/requirements.txt, malicious-smart-contract-ml-py/package-lock.json, malicious-smart-contract-ml-py/package.json, malicious-smart-contract-ml-py/requirements.txt, malicious-smart-contract-ml-py/src/agent.py, malicious-smart-contract-ml-py/src/constants.py, malicious-smart-contract-ml-py/src/findings.py, malicious-token-contract-ml-py/package-lock.json, malicious-token-contract-ml-py/package.json, malicious-token-contract-ml-py/requirements.txt, malicious-token-contract-ml-py/src/agent.py, malicious-token-contract-ml-py/src/constants.py, malicious-token-contract-ml-py/src/findings.py
* Reduce findings to 10 to prevent errors in 2 bots
* Enabled sharding for three bots with high tx drop rate.
=> Fix bot errors

alert-combiner-py/package-lock.json, alert-combiner-py/package.json, alert-combiner-py/src/L2Cache.py, alert-combiner-py/src/agent.py, alert-combiner-py/src/agent_test.py
Monitor L1 and create an alert only if at least one L2 alert exists.
=> Update alert combiner to monitor L1 when the current chain is an L2

entity-cluster-bot/src/agent.py, entity-cluster-bot/src/agent_test.py, entity-cluster-bot/src/constants.py, entity-cluster-bot/src/persistance.py
- Add prefix for different environments  in the db
- Improve persist test
=> Add prefix for different environments  in the db

scam-detector-py/package-lock.json, scam-detector-py/package.json, scam-detector-py/parseManualLists.py, scam-detector-py/publish.log, scam-detector-py/random_seed, scam-detector-py/release.md, scam-detector-py/src/agent.py, scam-detector-py/src/forta_explorer.py
up to v2.15.6, which is currently running in prod
=> Scam-detector-v2.15.5

cex-funding-py/package.json, cex-funding-py/src/agent.py, cex-funding-py/src/agent_test.py, cex-funding-py/src/constants.py
- Added missing `CEXES` data
- Refactored bot logic
- Added sharding configuration as a solution for [this issue](https://github.com/forta-network/starter-kits/issues/180)
=> Refactor cex funding

large-transfer-out-py/package.json
I did an investigation for [this issue](https://github.com/forta-network/starter-kits/issues/179), it seems sharding will fix the problem.
=> added sharding configuration for large-transfer bot

money-laundering-tornado-cash-py/package-lock.json, money-laundering-tornado-cash-py/package.json, money-laundering-tornado-cash-py/requirements.txt, money-laundering-tornado-cash-py/src/agent.py, money-laundering-tornado-cash-py/src/agent_test.py, money-laundering-tornado-cash-py/src/storage.py
Regarding issue: https://github.com/forta-network/starter-kits/issues/178
- Added shards 
- Used dynamodb to persist data
- Amended unit tests accordingly
=> Money laundering sharding

funding-tornado-cash-py/package.json, funding-tornado-cash-py/src/agent.py
Related issue: https://github.com/forta-network/starter-kits/issues/312
- replaced redundant and repetitive rpc calls with a variable 
- increased shards for ETH and BSC networks
=> Funding Tornado Cash Bot Sharding

positive-reputation-py/src/agent.py
fixed the bugs that are mentioned in https://github.com/forta-network/starter-kits/pull/318
=> Bug Fixing For Positive Reputation

scam-detector-py/src/findings.py, scam-detector-py/src/utils.py
- Adding unique key to `scam_finding()`
=> Scam Detector - Unique key 

scammer-label-propagation/.gitignore, scammer-label-propagation/Dockerfile, scammer-label-propagation/package-lock.json, scammer-label-propagation/package.json, scammer-label-propagation/publish.log, scammer-label-propagation/requirements.txt, scammer-label-propagation/src/agent.py, scammer-label-propagation/src/preprocessing/get_data.py
Addressing issue https://github.com/forta-network/starter-kits/issues/313#issuecomment-1770981816
Deactivating global model for ice phishing in the scammer label propagation
=> Scammer label propagation global ice phishing

scammer-label-propagation/package-lock.json, scammer-label-propagation/package.json, scammer-label-propagation/publish.log, scammer-label-propagation/requirements.txt
=> Updated version of the agent

alert-combiner-py/src/findings.py
Related issue: https://github.com/forta-network/starter-kits/issues/372
Added all `involved_addresses` into finding's `addresses` property.
example finding:
```
{
"name": "Attack detector identified an EOA with behavior consistent with an attack",
"description": "0xd0ccf523d198a9e0ef6222ad3d3e3f1919898725 likely involved in an attack preparation (0xdd276b19b8c9242077077d6589556bc7989d2cc510b927346b951a02b0438694).  Anomaly score: 0.00010383680854515402",
"alertId": "ATTACK-DETECTOR-PREPARATION",
"protocol": "ethereum",
"severity": "Critical",
"type": "Exploit",
"metadata": {
"attacker_address": "0xd0ccf523d198a9e0ef6222ad3d3e3f1919898725",
"anomaly_score_stage_Funding": 0.0009206863689960211,
"anomaly_score_stage_Preparation": 0.11278195490000001,
"anomaly_score": 0.00010383680854515402, …
```
=> AD: Stick addresses in addresses field

changenow-funding-py/package-lock.json, changenow-funding-py/package.json
- Added Avalanche, Arbitrum and Optimism to package.json
=> Update ChainIds at ChangeNow Funding Bot

anomalous-token-transfers-ml-py/src/utils/data_processing.py
- Fixed bug in fetching api key
=> Bug Fix in Anomalous Token Transfer ML Bot

unverified-contract-py/package-lock.json, unverified-contract-py/package.json, unverified-contract-py/src/agent.py
- Replaced Mutex with Lock
- Increased performance
- Fixed the bug that was putting the bot into infinite loops
=> Unverified Contract Bug Fix / Update

changenow-funding-py/src/agent.py
Related issue: https://github.com/forta-network/starter-kits/issues/436
=> ChangeNow Funding Performance Update

scam-detector-py/src/agent.py
related issue: https://github.com/forta-network/starter-kits/issues/420
- fp list is updated at the initialization
- added a checker in the following findings: 
- emit_ml_finding,
- emit_passthrough_finding,
- emit_contract_similarity_finding,
- emit_eoa_association_finding,
- emit_manual_finding
=> SD Manual FP List Check 

scam-detector-py/src/agent.py
related issue: https://github.com/forta-network/starter-kits/issues/421
=> SD Filter Labels by ChainID

malicious-smart-contract-ml-py/package-lock.json, malicious-smart-contract-ml-py/package.json, malicious-smart-contract-ml-py/src/agent.py, malicious-token-contract-ml-py/package-lock.json, malicious-token-contract-ml-py/package.json, malicious-token-contract-ml-py/src/agent.py, social-eng-contract-py/package-lock.json, social-eng-contract-py/package.json, social-eng-contract-py/src/agent.py, suspicious-contract-creation-py/package-lock.json, suspicious-contract-creation-py/package.json, suspicious-contract-creation-py/src/agent.py, unverified-contract-py/package-lock.json, unverified-contract-py/package.json, unverified-contract-py/src/agent.py
issue: https://github.com/forta-network/starter-kits/issues/440
=> Fix Calculating Contract Nonces
